seed_everything: 2969591811

data:
    class_path: clip_graph.data.datamodule.PubmedGraphTextDataModule
    init_args:
        data_dir: 'data/pubmed'
        seed: ${seed_everything}
        mlm: true
        batch_size: 72
        num_workers: -1
        pin_memory: true
        directed: true

        tokenizer_name: 'sentence-transformers/all-mpnet-base-v2'

        transductive: false
        transductive_identity_features: false
